name: bee-feed
dependencies:
- backports=1.0=py27_0
- click=6.6=py27_0
- decorator=4.0.10=py27_0
- enum34=1.1.6=py27_0
- feedparser=5.2.1=py27_0
- flask=0.11.1=py27_0
- get_terminal_size=1.0.0=py27_0
- ipython=4.2.0=py27_0
- ipython_genutils=0.1.0=py27_0
- itsdangerous=0.24=py27_0
- jinja2=2.8=py27_1
- markupsafe=0.23=py27_2
- openssl=1.0.2j=0
- path.py=8.2.1=py27_0
- pathlib2=2.1.0=py27_0
- pexpect=4.0.1=py27_0
- pickleshare=0.7.4=py27_0
- pip=8.1.2=py27_0
- ptyprocess=0.5.1=py27_0
- python=2.7.12=1
- readline=6.2=2
- setuptools=27.2.0=py27_0
- simplegeneric=0.8.1=py27_1
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- traitlets=4.3.1=py27_0
- werkzeug=0.11.11=py27_0
- wheel=0.29.0=py27_0
- zlib=1.2.8=3
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - ipython-genutils==0.1.0

